/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Diego
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lp = new javax.swing.JLabel();
        lc = new javax.swing.JLabel();
        lj = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        p = new javax.swing.JLabel();
        j = new javax.swing.JLabel();
        Perro = new javax.swing.JRadioButton();
        Caballo = new javax.swing.JRadioButton();
        Jirafa = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("SEGUNDO JUEGO", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lp.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lp.setForeground(new java.awt.Color(255, 255, 255));
        lp.setText("Hola soy un PERRO y me gusta que me acaricien la barriguita");
        jPanel2.add(lp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        lc.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lc.setForeground(new java.awt.Color(255, 255, 255));
        lc.setText("Hola soy un CABALLO y me gusta correr por el campo");
        jPanel2.add(lc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        lj.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lj.setForeground(new java.awt.Color(255, 255, 255));
        lj.setText("Hola soy un JIRAFA y tengo el cuello muy largo");
        jPanel2.add(lj, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caballo transparente.png"))); // NOI18N
        c.setText("a");
        jPanel2.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 150, 200));

        p.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perro transparente.png"))); // NOI18N
        jPanel2.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 130, 160));

        j.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jirafa trasnparente.png"))); // NOI18N
        j.setText("jir");
        jPanel2.add(j, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 140, 170));

        buttonGroup1.add(Perro);
        Perro.setText("Perro");
        jPanel2.add(Perro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 70, -1));

        buttonGroup1.add(Caballo);
        Caballo.setText("Caballo");
        jPanel2.add(Caballo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 70, -1));

        buttonGroup1.add(Jirafa);
        Jirafa.setText("Jirafa");
        Jirafa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JirafaActionPerformed(evt);
            }
        });
        jPanel2.add(Jirafa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/selva.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 460, 350));

        jTabbedPane1.addTab("MINIJUEGO 2", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JirafaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JirafaActionPerformed
       
    }//GEN-LAST:event_JirafaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton Caballo;
    public javax.swing.JRadioButton Jirafa;
    public javax.swing.JRadioButton Perro;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JLabel c;
    public javax.swing.JLabel j;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JLabel lc;
    public javax.swing.JLabel lj;
    public javax.swing.JLabel lp;
    public javax.swing.JLabel p;
    // End of variables declaration//GEN-END:variables
}
